id: P004232
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:03:24.048995
source_metadata:
  id: bdr:W2DB4606
  title: 'སྔགས་མང་ཞིབ་འཇུག ༼༤༽ '
  author: ''
  volumes:
    32740e7c0a0d4a558bdce46212af79fe:
      image_group_id: I1PD27263
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
