id: IB5BF1A7A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:23:01+00:00'
last_modified: '2022-06-07T21:16:16.106869+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4606
  title: 'སྔགས་མང་ཞིབ་འཇུག ༼༤༽ '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '6621':
      image_group_id: I1PD27263
      title: ''
      total_pages: 134
      order: 1
      base_file: 6621.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
